# Generated by Django 4.2.21 on 2026-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H_Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('attribute', models.JSONField(default=dict, verbose_name='Attribute')),
                ('locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('red_day', models.BooleanField(default=False, verbose_name='RedDay')),
            ],
        ),
    ]
