# Generated by Django 3.0.3 on 2020-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneday',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='oneday',
            name='attribute',
            field=models.CharField(max_length=100, verbose_name='Attr'),
        ),
        migrations.AlterField(
            model_name='oneday',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
