# Generated by Django 3.0.3 on 2020-04-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_hour', models.IntegerField(verbose_name='StartHour')),
                ('start_min', models.IntegerField(verbose_name='StartHour')),
                ('end_hour', models.IntegerField(verbose_name='StartHour')),
                ('end_min', models.IntegerField(verbose_name='StartHour')),
                ('work_hours', models.FloatField(verbose_name='WorkHours')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='DemandOfStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(verbose_name='weekdayDemand')),
                ('holiday', models.IntegerField(verbose_name='holidayDemand')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Shift', verbose_name='Shift')),
            ],
        ),
    ]
