# Generated by Django 3.0.3 on 2020-04-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandofstation',
            name='level',
            field=models.IntegerField(default=1, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='demandofstation',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station', verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='demandofstation',
            name='holiday',
            field=models.IntegerField(default=0, verbose_name='holidayDemand'),
        ),
        migrations.AlterField(
            model_name='demandofstation',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='demandofstation',
            name='weekday',
            field=models.IntegerField(default=0, verbose_name='weekdayDemand'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_hour',
            field=models.IntegerField(null=True, verbose_name='StartHour'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_min',
            field=models.IntegerField(null=True, verbose_name='StartHour'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_hour',
            field=models.IntegerField(null=True, verbose_name='StartHour'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_min',
            field=models.IntegerField(null=True, verbose_name='StartHour'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='work_hours',
            field=models.FloatField(null=True, verbose_name='WorkHours'),
        ),
    ]
