# Generated by Django 3.0.3 on 2020-04-10 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20200409_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='station',
        ),
        migrations.DeleteModel(
            name='DemandOfStation',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
