# Generated by Django 3.0.3 on 2020-05-08 01:49

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department')),
                ('detail', models.CharField(max_length=100, verbose_name='Detail')),
                ('manager_num', models.IntegerField(default=2, verbose_name='managerNum')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='FullName')),
                ('level', models.IntegerField(choices=[(4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N, N1')], null=True, verbose_name='Level')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('user', 'user')], max_length=100, null=True, verbose_name='Role')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='None', max_length=20, verbose_name='Gender')),
                ('type_of_user', models.CharField(choices=[('Normal', 'Normal'), ('Pregnant', 'Pregnant'), ('Intern', 'Intern'), ('PartTime', 'PartTime')], default='Normal', max_length=20, verbose_name='Type')),
                ('can_be_scheduled', models.BooleanField(default=True, null=True, verbose_name='CanBeScheduled')),
                ('holiday_rest_num', models.IntegerField(null=True, verbose_name='HolidayRestNum')),
                ('holiday_rest_num_used', models.IntegerField(default=0, null=True, verbose_name='HolidayRestNumUsed')),
                ('special_rest_num', models.IntegerField(null=True, verbose_name='SpecialRestNum')),
                ('special_rest_num_used', models.IntegerField(default=0, null=True, verbose_name='SpecialRestNumUsed')),
                ('eid', models.CharField(max_length=100, null=True, verbose_name='EmployeeId')),
                ('hour_required', models.FloatField(default=0.0, null=True, verbose_name='HourRequired')),
                ('hour_realized', models.FloatField(default=0.0, null=True, verbose_name='HourRealized')),
                ('onboard_date', models.DateField(null=True, verbose_name='OnboardDate')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department', verbose_name='Department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
