# Generated by Django 4.2.21 on 2026-04-28 08:28

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='姓名')),
                ('job_title', models.CharField(max_length=100, null=True, verbose_name='職稱')),
                ('level', models.IntegerField(choices=[(4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N1'), (5, 'Nn')], null=True, verbose_name='職級')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], max_length=100, null=True, verbose_name='權限')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=20, null=True, verbose_name='性別')),
                ('type_of_user', models.IntegerField(choices=[(0, '正職'), (1, '資深正職'), (2, '行政職'), (3, '新進人員'), (4, '兼職人員'), (5, '實習生')], default=0, null=True, verbose_name='排班身份')),
                ('pregnant', models.BooleanField(default=False, null=True, verbose_name='其他')),
                ('can_be_scheduled', models.BooleanField(default=True, null=True, verbose_name='排班狀況')),
                ('holiday_rest_num', models.IntegerField(default=10, null=True, verbose_name='假日休假數')),
                ('holiday_rest_num_used', models.IntegerField(default=0, null=True, verbose_name='已休假日休假數')),
                ('special_rest_num', models.IntegerField(default=10, null=True, verbose_name='特休')),
                ('special_rest_num_used', models.IntegerField(default=0, null=True, verbose_name='累計已休特休')),
                ('eid', models.CharField(max_length=100, null=True, verbose_name='工號')),
                ('hour_required', models.FloatField(default=0.0, null=True, verbose_name='應排班時數')),
                ('hour_realized', models.FloatField(default=0.0, null=True, verbose_name='已排班時數')),
                ('onboard_date', models.DateField(null=True, verbose_name='到職日')),
                ('compensatory_rest', models.IntegerField(default=0, null=True, verbose_name='剩餘補休')),
                ('starting_month', models.IntegerField(default=1, null=True, verbose_name='起始月')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='簡稱')),
                ('detail', models.CharField(max_length=100, unique=True, verbose_name='科別名稱')),
                ('limit_pre_schedule', models.IntegerField(default=3, verbose_name='預約休假數量')),
                ('deadline_pre_schedule', models.IntegerField(default=19, verbose_name='預約休假期限')),
                ('reset', models.IntegerField(default=0, verbose_name='時數重置規則')),
                ('law_rule', models.IntegerField(choices=[(0, '一般工時，7休2'), (1, '雙週變形工時，14休4'), (2, '四週變形工時，28休8'), (3, '八週變形工時，56休16')], default=0, verbose_name='勞基法工時規則')),
                ('schedule_rule', models.IntegerField(choices=[(0, '單週同班種'), (1, '單月同班種'), (2, '三月同班種')], default=0, verbose_name='班種設定')),
                ('admin_in_schedule', models.BooleanField(default=False, verbose_name='管理者是否排班')),
                ('same_day_notice', models.IntegerField(default=5, verbose_name='預約休假日人數過多提示')),
                ('date_start', models.DateField(default=datetime.date(2020, 6, 9), verbose_name='起算日期')),
                ('start_of_week', models.IntegerField(choices=[(0, '星期日'), (1, '星期一')], default=0, verbose_name='週起始日')),
                ('can_rest_redday', models.IntegerField(default=10, null=True, verbose_name='週末及國定假日可休數量')),
                ('overtime_rule', models.IntegerField(choices=[(0, '單月46小時'), (1, '單月54小時, 三個月138小時')], default=0, null=True, verbose_name='加班規則')),
                ('month_cycle', models.IntegerField(default=1, null=True, verbose_name='月週期')),
            ],
        ),
        migrations.CreateModel(
            name='Liscense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='Name')),
                ('date', models.DateField(verbose_name='LiscenseDate')),
                ('due', models.DateField(verbose_name='DueDate')),
                ('source', models.CharField(max_length=25, verbose_name='Source')),
                ('liscense_pic', models.ImageField(blank=True, null=True, upload_to='liscense', verbose_name='LiscensePic')),
                ('liscense_pic_2', models.ImageField(blank=True, null=True, upload_to='liscense', verbose_name='LiscensePic2')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department', verbose_name='科別')),
                ('manager_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mgr1', to=settings.AUTH_USER_MODEL, verbose_name='管理者1')),
                ('manager_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mgr2', to=settings.AUTH_USER_MODEL, verbose_name='管理者2')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department', verbose_name='科別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
