# Generated by Django 3.0.3 on 2020-04-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200408_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_be_scheduled',
            field=models.BooleanField(default=True, null=True, verbose_name='CanBeScheduled'),
        ),
    ]
