# Generated by Django 3.0.3 on 2020-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200414_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='holiday_rest_num_used',
            field=models.IntegerField(null=True, verbose_name='HolidayRestNumUsed'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='special_rest_num_used',
            field=models.IntegerField(null=True, verbose_name='SpecialRestNum'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Pragnant', 'Pragnant'), ('Intern', 'Intern'), ('PartTime', 'PartTime')], default='Normal', max_length=20, verbose_name='Type'),
        ),
    ]
