# Generated by Django 3.0.3 on 2020-05-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='holiday_rest_num_used',
            field=models.IntegerField(default=0, null=True, verbose_name='HolidayRestNumUsed'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='special_rest_num_used',
            field=models.IntegerField(default=0, null=True, verbose_name='SpecialRestNumUsed'),
        ),
    ]
