# Generated by Django 3.0.3 on 2020-05-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200505_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(choices=[(4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N, N1')], null=True, verbose_name='Level'),
        ),
    ]
