# Generated by Django 3.0.3 on 2020-05-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200505_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Pregnant', 'Pregnant'), ('Intern', 'Intern'), ('PartTime', 'PartTime')], default='Normal', max_length=20, verbose_name='Type'),
        ),
    ]
