# Generated by Django 4.2.21 on 2026-04-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('user', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PromiseShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('shift_type', models.IntegerField(choices=[(0, '事假'), (1, '家庭照顧假'), (2, '無薪病假'), (3, '公假'), (4, '產假'), (5, '例/休'), (6, '生理假'), (7, '特休'), (8, '補休'), (9, '婚假'), (10, '計薪病假'), (11, '喪假'), (12, '安胎休養假'), (13, '產檢假'), (14, '陪產假')], null=True, verbose_name='類型')),
                ('hours', models.IntegerField(null=True, verbose_name='時數')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='備註')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
