# Generated by Django 3.0.3 on 2020-04-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='shift',
        ),
    ]
