# Generated by Django 3.0.3 on 2020-05-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_shift_shift_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_remove_reservation_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('date', models.DateField(verbose_name='Date')),
                ('shift', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='shift.Shift', verbose_name='Shiftv')),
                ('user', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
