# Generated by Django 3.0.3 on 2020-05-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_shift_shift_type'),
        ('reservation', '0003_promiseshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promiseshift',
            name='shift',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='shift.Shift', verbose_name='Shift'),
        ),
    ]
