# Generated by Django 4.2.21 on 2026-04-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('shift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandOfStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='分級')),
                ('config1', models.IntegerField(default=0, verbose_name='配置1')),
                ('config2', models.IntegerField(default=0, verbose_name='配置2')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shift', verbose_name='Shift')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.station', verbose_name='Station')),
            ],
            options={
                'unique_together': {('station', 'shift', 'level')},
            },
        ),
        migrations.CreateModel(
            name='DemandUserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demand.demandofstation', verbose_name='DemandOfStation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
