# Generated by Django 3.0.3 on 2020-05-08 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandOfStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, null=True, verbose_name='level')),
                ('weekday', models.IntegerField(default=0, verbose_name='weekdayDemand')),
                ('holiday', models.IntegerField(default=0, verbose_name='holidayDemand')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.Shift', verbose_name='Shift')),
            ],
        ),
    ]
