# Generated by Django 3.0.3 on 2020-04-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandofstation',
            name='station',
        ),
    ]
