# Generated by Django 4.2.21 on 2026-04-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('result', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='內容')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department', verbose_name='科別')),
            ],
        ),
        migrations.CreateModel(
            name='ResultRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remarks.remarksquare', verbose_name='備註')),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='result.result', verbose_name='班表')),
            ],
        ),
        migrations.CreateModel(
            name='PreResultRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remarks.remarksquare', verbose_name='備註')),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='result.preresult', verbose_name='班表')),
            ],
        ),
        migrations.CreateModel(
            name='UserRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(null=True, verbose_name='月份')),
                ('content', models.TextField(blank=True, max_length=100, null=True, verbose_name='備註')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
