# Generated by Django 3.0.3 on 2020-05-08 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_pre_schedule', models.IntegerField(default=3, null=True, verbose_name='LimitPreSchedule')),
                ('deadline_pre_schedule', models.IntegerField(default=19, null=True, verbose_name='DeadlinePreSchedule')),
                ('holiday_rest', models.IntegerField(default=40, null=True, verbose_name='HolidayRest')),
                ('reset_month', models.IntegerField(default=1, verbose_name='ResetMonth')),
                ('reset_day', models.IntegerField(default=1, verbose_name='ResetDay')),
                ('law_rule', models.IntegerField(default=1, null=True, verbose_name='LawRule')),
                ('schedule_rule', models.IntegerField(default=1, null=True, verbose_name='ScheduleRule')),
                ('admin_in_schedule', models.BooleanField(default=False, verbose_name='AdminInSchedule')),
                ('part_time_in_holiday', models.BooleanField(default=False, verbose_name='PartTimeInHoliday')),
                ('intern_in_holiday', models.BooleanField(default=False, verbose_name='InternInHoliday')),
                ('intern_d_only', models.BooleanField(default=True, verbose_name='InternDOnly')),
                ('same_day_notice', models.IntegerField(default=5, verbose_name='SameDayNotice')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department', verbose_name='Department')),
            ],
        ),
    ]
