# Generated by Django 3.0.3 on 2020-04-30 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20200414_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('limit_pre_schedule', models.IntegerField(default=3, null=True, verbose_name='LimitPreSchedule')),
                ('deadline_pre_schedule', models.IntegerField(default=19, null=True, verbose_name='DeadlinePreSchedule')),
                ('holiday_rest', models.IntegerField(default=40, null=True, verbose_name='HolidayRest')),
                ('recal_workhour_date', models.CharField(default='1/1', max_length=5, verbose_name='RecalWorkHourDate')),
                ('law_rule', models.IntegerField(default=1, null=True, verbose_name='LawRule')),
                ('schedule_rule', models.IntegerField(default=1, null=True, verbose_name='ScheduleRule')),
                ('admin_in_schedule', models.BooleanField(default=False, verbose_name='AdminInSchedule')),
                ('part_time_in_holiday', models.BooleanField(default=False, verbose_name='PartTimeInHoliday')),
                ('intern_in_holiday', models.BooleanField(default=False, verbose_name='InternInHoliday')),
                ('intern_d_only', models.BooleanField(default=True, verbose_name='InternDOnly')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department', verbose_name='Department')),
            ],
        ),
    ]
