# Generated by Django 3.0.3 on 2020-05-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='reset_day',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='reset_month',
        ),
        migrations.AddField(
            model_name='condition',
            name='reset',
            field=models.IntegerField(default=0, verbose_name='Reset'),
        ),
    ]
