# Generated by Django 3.0.3 on 2020-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0002_remove_condition_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='recal_workhour_date',
        ),
        migrations.AddField(
            model_name='condition',
            name='reset_day',
            field=models.IntegerField(default=1, verbose_name='ResetDay'),
        ),
        migrations.AddField(
            model_name='condition',
            name='reset_month',
            field=models.IntegerField(default=1, verbose_name='ResetMonth'),
        ),
    ]
