# Generated by Django 3.0.3 on 2020-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0003_auto_20200504_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='same_day_notice',
            field=models.IntegerField(default=5, verbose_name='SameDayNotice'),
        ),
    ]
