# Generated by Django 4.2.21 on 2026-04-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('shift_type', models.IntegerField(choices=[(0, '白班'), (1, '小夜'), (2, '大夜'), (3, '公假'), (4, 'oncall'), (5, '有薪假'), (6, '無薪假'), (7, '行政')], null=True, verbose_name='ShiftType')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='代碼')),
                ('start_time', models.TimeField(null=True, verbose_name='StartTime')),
                ('end_time', models.TimeField(null=True, verbose_name='EndTime')),
                ('work_hours', models.FloatField(null=True, verbose_name='WorkHours')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department', verbose_name='Department')),
            ],
        ),
    ]
