# Generated by Django 3.0.3 on 2020-05-08 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('shift_type', models.CharField(max_length=100, null=True, verbose_name='ShiftType')),
                ('start_hour', models.IntegerField(null=True, verbose_name='StartHour')),
                ('start_min', models.IntegerField(null=True, verbose_name='StartHour')),
                ('end_hour', models.IntegerField(null=True, verbose_name='StartHour')),
                ('end_min', models.IntegerField(null=True, verbose_name='StartHour')),
                ('work_hours', models.FloatField(null=True, verbose_name='WorkHours')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station', verbose_name='Station')),
            ],
        ),
    ]
