# Generated by Django 3.0.3 on 2020-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(max_length=100, null=True, verbose_name='ShiftType'),
        ),
    ]
